# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('chevere', models.IntegerField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UsTw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.BooleanField()),
                ('twittid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Twitts.Twitts')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='twitts',
            name='user',
            field=models.ManyToManyField(through='Twitts.UsTw', to=settings.AUTH_USER_MODEL),
        ),
    ]
